name: Sync repos in this organization to gitee/tiddly-gittly

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: gitee
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的Github用户（源）
          src: github/tiddly-gittly
          # 必选，需要同步到的Gitee的用户（目的）
          dst: gitee/tiddly-gittly
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          account_type: org
          black_list: 'sync-gitee'
          force_update: true
          debug: true
          mappings: "TiddlyWiki-CPL=>tiddly-wiki-cpl"
